import ThemeComponent from "@/core/theme/ThemeComponent";
import { StoreProvider } from "@/store/StoreProvider";
import SnackBarComponent from "@/core/components/SnackBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <ThemeComponent>
          <body>
            {children}
            <SnackBarComponent />
          </body>
        </ThemeComponent>
      </StoreProvider>
    </html>
  );
}
